[tox]
envlist = py313
skipsdist = True
[testenv]
description = Full local testing environment (minus code coverage)
skip_install = true
passenv =
    APP_CODE
    ENV
    LOG_DIR
    LOG_LEVEL
    PYTHONPATH
setenv =
deps=
    -r requirements.txt
    -r requirements-test.txt    
allowlist_externals =
    black
    pylint
    pycodestyle
    coverage
    pytest
    bandit
    pip-audit
commands =
    pip install --upgrade pip
    black src tests
    pylint --rcfile=tox.ini src
    pylint --rcfile=tox.ini --disable=C0103 tests
    pycodestyle src tests
    bandit -r src
    pip-audit -r requirements.txt
[testenv:po]
description = pytest only - discrete local testing wit pos args
skip_install = true
deps =
    -r requirements.txt
    -r requirements-test.txt    
allowlist_externals = 
    pytest
    sudo
passenv =
    APP_CODE
    ENV
    LOG_DIR
    LOG_LEVEL
    PYTHONPATH
setenv =
commands =
    sudo env PYTHONPATH=/home/cp/git/py_lumen/src   /home/cp/git/py_lumen/.venv/bin/python -m pytest --color=yes {posargs}
[pycodestyle]
max-line-length = 90
ignore = E126, W503, W504, E203
exclude = .tox, .venv,
[pytest]
log_cli = 1
log_cli_level = INFO
log_cli_format = "%(asctime)s [%(levelname)8s] [%(filename)s:%(lineno)s] - %(message)s"
asyncio_mode = auto
addopts = -vxs -p no:warnings
testpaths = tests/pytest
norecursedirs = src/xform/dbt_packages
filterwarnings =
    ignore::UserWarning:genbadge.utils_badge
[coverage:run]
parallel = True
branch = True
concurrency = multiprocessing
data_file=/app/tests/.coverage
relative_files = True
disable_warnings = couldnt-parse
source = /app/src 
omit=
    */.github/*
    */.tox/*
    */.venv/*
    */data/*
    */deploy/*
    */scripts/*
    */tests/*
[coverage:paths]
source =
    /app/src
    src
    /usr/local/lib/python3.11/site-packages/achat
[coverage:report]                   
ignore_errors = True
[pylint]
ignore-paths = src/xform/dbt_packages
disable=
    # Classes should wrap more than 3 functions public and internal
    # Do not focus on public  
    too-few-public-methods,
    # Using TODO's is ok and helpful for tracking roadmap alignment
    fixme,
    # need a better docstring strategy this is probably too lazy
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,
    