[tox]
envlist = py313
skipsdist = True
[testenv]
description = Full local testing environment (minus code coverage)
skip_install = true
passenv =
    APP_CODE
    ENV
    LOG_DIR
    LOG_LEVEL
    PYTHONPATH
setenv =
deps=
    -r requirements.txt
    -r requirements-test.txt    
allowlist_externals =
    black
    pylint
    pycodestyle
    coverage
    bandit
    pip-audit
    sudo
commands =
    pip install --upgrade pip
    black src
    pylint --rcfile=tox.ini src
    pycodestyle src
    bandit -r src
    pip-audit -r requirements.txt
[pycodestyle]
max-line-length = 90
ignore = E126, W503, W504, E203
exclude = .tox, .venv,
[pylint]
ignore-paths = src/xform/dbt_packages
disable=
    # Classes should wrap more than 3 functions public and internal
    # Do not focus on public  
    too-few-public-methods,
    # Using TODO's is ok and helpful for tracking roadmap alignment
    fixme,
    # need a better docstring strategy this is probably too lazy
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,
    